#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2012, OpenNebula Project Leads (OpenNebula.org)             #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

###############################################################################
# This script is used to remove a VM image (SRC) from the image repository 
###############################################################################


###############################################################################
# Prepare environment
###############################################################################

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

. /var/lib/one/remotes/scripts_common.sh

DRIVER_PATH=$(dirname $0)
source ${DRIVER_PATH}/../libfs.sh

## Include file with LVM helpers definition
. /etc/one/tm/gfs2clvmrc


###############################################################################
# Get 'rm' and Datastore arguments from OpenNebula core
###############################################################################

DRV_ACTION=$1
ID=$2

XPATH="${DRIVER_PATH}/../xpath.rb -b $DRV_ACTION"

unset i XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /DS_DRIVER_ACTION_DATA/IMAGE/SOURCE \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/BASE_PATH)

SRC="${XPATH_ELEMENTS[0]}"
BASE_PATH="${XPATH_ELEMENTS[1]}"

BASENAME_SRC=`basename "${SRC##$BASE_PATH}"`


###############################################################################
# Determine Volume Group name by Datastore ID/Name
###############################################################################

DSID=$(echo $BASE_PATH | cut -f6 -d"/")
VG_NAME=$(onedatastore show ${DSID} | grep NAME | awk '{print $3}')
CLUSTER=$(onedatastore show ${DSID} | grep CLUSTER | awk '{print $3}')


###############################################################################
# Remove the image from the repository
###############################################################################

SRC_BASENAME=$( basename "$SRC" )

HOSTID=$(onehost list -l ID,NAME,STAT,CLUSTER | grep ${CLUSTER} | grep on | head -n 1 | awk '{print $1}')
hostname=$(onehost show ${HOSTID} | grep HOSTNAME | cut -f2 -d'"')
log "hostname: $hostname"
exec_and_log "ssh $hostname sudo lvremove -f ${VG_NAME}/lv-oneimg-${SRC_BASENAME}" \
    "Error deleting ${VG_NAME}/lv-oneimg-${SRC_BASENAME}"
